QT_VERSION_MAJOR := 6
ANYKEEP_CMAKE_ARGS := -DANYKEEP_XMPP_BACKEND=IRIS -DANYKEEP_BUILD_BUNDLED_QCA=OFF -DANYKEEP_BUILD_BUNDLED_IRIS=OFF -DANYKEEP_BUILD_BUNDLED_QXMPP=OFF -DANYKEEP_BUILD_BUNDLED_QCORO=OFF -DANYKEEP_BUILD_BUNDLED_QTKEYCHAIN=OFF -DANYKEEP_ALLOW_SOURCE_DEPENDENCY_FALLBACKS=OFF -DBUILD_TESTING=OFF
