cmake_minimum_required(VERSION 3.25)

foreach(required_var IN ITEMS RUNTIME_ROOT OUTPUT_PATH VERSION IDENTITY_NAME PUBLISHER PUBLISHER_DISPLAY_NAME
                              MANIFEST_TEMPLATE ASSETS_DIR MAKEAPPX_EXECUTABLE WORK_ROOT MIN_WINDOWS_VERSION
                              MAX_WINDOWS_VERSION_TESTED VCLIBS_NAME VCLIBS_MIN_VERSION VCLIBS_PUBLISHER)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()

if(NOT EXISTS "${MAKEAPPX_EXECUTABLE}")
    message(FATAL_ERROR "MakeAppx.exe was not found at '${MAKEAPPX_EXECUTABLE}'")
endif()
if(NOT IS_DIRECTORY "${RUNTIME_ROOT}")
    message(FATAL_ERROR "Windows runtime tree was not found at '${RUNTIME_ROOT}'")
endif()
if(NOT EXISTS "${RUNTIME_ROOT}/anykeep.exe")
    message(FATAL_ERROR "The runtime tree does not contain anykeep.exe: '${RUNTIME_ROOT}'")
endif()
if(NOT EXISTS "${MANIFEST_TEMPLATE}")
    message(FATAL_ERROR "MSIX manifest template was not found: '${MANIFEST_TEMPLATE}'")
endif()
if(NOT IS_DIRECTORY "${ASSETS_DIR}")
    message(FATAL_ERROR "MSIX Assets directory was not found: '${ASSETS_DIR}'")
endif()

string(LENGTH "${IDENTITY_NAME}" identity_name_length)
if(identity_name_length LESS 3 OR identity_name_length GREATER 50 OR NOT IDENTITY_NAME MATCHES "^[A-Za-z0-9.-]+$")
    message(FATAL_ERROR "IDENTITY_NAME must be a 3-50 character MSIX package string (letters, digits, dot, dash): '${IDENTITY_NAME}'")
endif()
if(NOT VERSION MATCHES "^([0-9]+)[.]([0-9]+)[.]([0-9]+)[.]([0-9]+)$")
    message(FATAL_ERROR "VERSION must be an MSIX four-part numeric version, got '${VERSION}'")
endif()
set(msix_version_major "${CMAKE_MATCH_1}")
set(msix_version_revision "${CMAKE_MATCH_4}")
foreach(version_component IN ITEMS CMAKE_MATCH_1 CMAKE_MATCH_2 CMAKE_MATCH_3 CMAKE_MATCH_4)
    if(${version_component} GREATER 65535)
        message(FATAL_ERROR "MSIX version component exceeds 65535 in '${VERSION}'")
    endif()
endforeach()
if(msix_version_major EQUAL 0)
    message(FATAL_ERROR "Microsoft Store MSIX versions must have a non-zero major component: '${VERSION}'")
endif()
if(NOT msix_version_revision EQUAL 0)
    message(FATAL_ERROR "Microsoft Store reserves the fourth MSIX version component; it must be 0: '${VERSION}'")
endif()

function(xml_escape input output)
    set(value "${input}")
    string(REPLACE "&" "&amp;" value "${value}")
    string(REPLACE "<" "&lt;" value "${value}")
    string(REPLACE ">" "&gt;" value "${value}")
    string(REPLACE "\"" "&quot;" value "${value}")
    string(REPLACE "'" "&apos;" value "${value}")
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

get_filename_component(output_dir "${OUTPUT_PATH}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
file(REMOVE_RECURSE "${WORK_ROOT}")
set(package_root "${WORK_ROOT}/package")
file(MAKE_DIRECTORY "${package_root}")

# The normal Windows runtime tree is shared with MSI packaging. Store packages
# launch anykeep.exe directly and let Microsoft Store own updates, so do not
# include the stable MSI launcher or the self-update helper in the MSIX.
file(COPY "${RUNTIME_ROOT}/" DESTINATION "${package_root}")
file(REMOVE "${package_root}/AnyKeepLauncher.exe" "${package_root}/AnyKeepUpdater.exe")
if(NOT EXISTS "${package_root}/anykeep.exe")
    message(FATAL_ERROR "anykeep.exe disappeared while preparing the MSIX staging tree")
endif()

file(COPY "${ASSETS_DIR}/" DESTINATION "${package_root}/Assets")

xml_escape("${IDENTITY_NAME}" MSIX_IDENTITY_NAME_XML)
xml_escape("${PUBLISHER}" MSIX_PUBLISHER_XML)
xml_escape("${PUBLISHER_DISPLAY_NAME}" MSIX_PUBLISHER_DISPLAY_NAME_XML)
xml_escape("${VERSION}" MSIX_VERSION_XML)
xml_escape("${MIN_WINDOWS_VERSION}" MSIX_MIN_WINDOWS_VERSION_XML)
xml_escape("${MAX_WINDOWS_VERSION_TESTED}" MSIX_MAX_WINDOWS_VERSION_TESTED_XML)
xml_escape("${VCLIBS_NAME}" MSIX_VCLIBS_NAME_XML)
xml_escape("${VCLIBS_MIN_VERSION}" MSIX_VCLIBS_MIN_VERSION_XML)
xml_escape("${VCLIBS_PUBLISHER}" MSIX_VCLIBS_PUBLISHER_XML)
configure_file("${MANIFEST_TEMPLATE}" "${package_root}/AppxManifest.xml" @ONLY)

file(REMOVE "${OUTPUT_PATH}")
execute_process(
    COMMAND "${MAKEAPPX_EXECUTABLE}" pack /d "${package_root}" /p "${OUTPUT_PATH}" /o
    RESULT_VARIABLE makeappx_result
    OUTPUT_VARIABLE makeappx_stdout
    ERROR_VARIABLE makeappx_stderr)
if(NOT makeappx_result EQUAL 0)
    message(FATAL_ERROR "MakeAppx failed (${makeappx_result}):\n${makeappx_stdout}\n${makeappx_stderr}")
endif()
if(NOT EXISTS "${OUTPUT_PATH}")
    message(FATAL_ERROR "MakeAppx reported success but did not produce '${OUTPUT_PATH}'")
endif()
file(SIZE "${OUTPUT_PATH}" msix_size)
if(msix_size LESS 1024)
    message(FATAL_ERROR "Generated MSIX is unexpectedly small (${msix_size} bytes): '${OUTPUT_PATH}'")
endif()

message(STATUS "Built Microsoft Store MSIX: ${OUTPUT_PATH}")
message(STATUS "MSIX identity: ${IDENTITY_NAME}")
message(STATUS "MSIX publisher: ${PUBLISHER}")
message(STATUS "MSIX version: ${VERSION}")
