<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:xmpp:qtnote:storage:1"
           xmlns="urn:xmpp:qtnote:storage:1"
           xmlns:note="urn:xmpp:qtnote:note:1"
           elementFormDefault="qualified">
  <xs:import namespace="urn:xmpp:qtnote:note:1" schemaLocation="qtnote-note.xsd"/>
  <xs:simpleType name="versionType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+\.[0-9]+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="envelope">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="node" type="xs:string"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="required">
            <xs:complexType>
              <xs:attribute name="feature" type="xs:anyURI" use="required"/>
            </xs:complexType>
          </xs:element>
          <xs:any namespace="##other" processContents="lax"/>
        </xs:choice>
        <xs:element name="content">
          <xs:complexType>
            <xs:choice>
              <xs:element ref="note:index"/>
              <xs:element ref="note:note"/>
            </xs:choice>
            <xs:anyAttribute processContents="lax"/>
          </xs:complexType>
        </xs:element>
        <xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
      </xs:sequence>
      <xs:attribute name="wire" type="versionType" use="required"/>
      <xs:attribute name="schema" type="versionType" use="required"/>
      <xs:anyAttribute processContents="lax"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
